### ISSUE TITLE
Possible additions

### ISSUE THREAD

**Issue by BBlackwo** [basarat/awesome-enterprise-component-library#2]
Here are a few suggestions of libraries that could be added to this list. Not sure if they're really "enterprise" though.

- https://ux.mailchimp.com/patterns/color
- https://polaris.shopify.com/
- https://feelix.myob.com/

**Comment by BBlackwo** [comment]
Now that I've started digging (https://designsystemsrepo.com/design-systems/) there are so many out there! :O 

- https://design.gitlab.com/
- https://protocol.mozilla.org/
- https://stackoverflow.design/product/guidelines/using-stacks
- https://garden.zendesk.com/

**Comment by basarat** [comment]
https://github.com/basarat/awesome-enterprise-component-library/commit/50f6c63ebceb0a66675f919a8ec20f22ae281433 :rose:
